"""
Manual enemy skill cooldown tracker.

Ability data is loaded from assets/hero_abilities.json (generated by
tools/fetch_abilities.py from dotaconstants — 127 heroes, all abilities).

The frontend sends:
  {"type": "cooldown_trigger",
   "hero": "antimage", "ability": "Blink", "level": 3, "player_slot": 0}

This tracker starts a countdown and broadcasts remaining time via WebSocket.
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ── Load ability database ─────────────────────────────────────────────────────

_DB_PATH = Path(__file__).parent.parent / "assets" / "hero_abilities.json"

def _load_db() -> dict:
    if not _DB_PATH.exists():
        return {}
    return json.loads(_DB_PATH.read_text(encoding="utf-8"))

ABILITY_DB: dict = _load_db()   # hero_key → {display_name, abilities: [...]}


# ── Data helpers ──────────────────────────────────────────────────────────────

def get_hero_list() -> list[dict]:
    """Return [{key, display_name}] sorted by display_name."""
    return sorted(
        [{"key": k, "display_name": v["display_name"]} for k, v in ABILITY_DB.items()],
        key=lambda h: h["display_name"],
    )

def get_abilities(hero_key: str) -> list[dict]:
    """Return ability list for a hero."""
    hero = ABILITY_DB.get(hero_key)
    if not hero:
        return []
    return hero["abilities"]   # [{name, display_name, cooldowns, max_level}]

def cooldown_for(hero_key: str, ability_name: str, level: int) -> Optional[float]:
    for ab in get_abilities(hero_key):
        if ab["name"] == ability_name or ab["display_name"].lower() == ability_name.lower():
            cds = ab["cooldowns"]
            idx = max(0, min(level - 1, len(cds) - 1))
            cd = cds[idx]
            return cd if cd > 0 else None
    return None


# ── Active cooldown tracking ──────────────────────────────────────────────────

@dataclass
class ActiveCooldown:
    id: str
    hero: str
    hero_display: str
    ability: str
    ability_display: str
    duration: float
    started_at: float
    player_slot: int          # 0-4 for enemy team

    @property
    def remaining(self) -> float:
        return max(0.0, self.duration - (time.monotonic() - self.started_at))

    @property
    def is_expired(self) -> bool:
        return self.remaining == 0.0

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "hero": self.hero,
            "hero_display": self.hero_display,
            "ability": self.ability,
            "ability_display": self.ability_display,
            "player_slot": self.player_slot,
            "duration": self.duration,
            "remaining": round(self.remaining, 1),
            "started_at": self.started_at,
        }


class CooldownTracker:
    def __init__(self) -> None:
        self._active: dict[str, ActiveCooldown] = {}

    def trigger(
        self,
        hero: str,
        ability: str,
        level: int,
        player_slot: int,
    ) -> Optional[dict]:
        """Start cooldown. Returns dict or None if hero/ability unknown."""
        hero_info = ABILITY_DB.get(hero)
        if not hero_info:
            return None

        cd = cooldown_for(hero, ability, level)
        if cd is None:
            return None

        ability_display = ability
        for ab in hero_info["abilities"]:
            if ab["name"] == ability or ab["display_name"].lower() == ability.lower():
                ability_display = ab["display_name"]
                break

        # Replace existing cooldown for same hero+ability+slot
        existing = self._find_existing(hero, ability, player_slot)
        if existing:
            del self._active[existing]

        entry = ActiveCooldown(
            id=str(uuid.uuid4()),
            hero=hero,
            hero_display=hero_info["display_name"],
            ability=ability,
            ability_display=ability_display,
            duration=cd,
            started_at=time.monotonic(),
            player_slot=player_slot,
        )
        self._active[entry.id] = entry
        return entry.to_dict()

    def tick(self) -> list[str]:
        """Prune expired. Returns list of expired IDs."""
        expired = [i for i, cd in self._active.items() if cd.is_expired]
        for i in expired:
            del self._active[i]
        return expired

    def status(self) -> list[dict]:
        self.tick()
        return [cd.to_dict() for cd in self._active.values()]

    def list_heroes(self) -> list[dict]:
        return get_hero_list()

    def get_abilities(self, hero_key: str) -> list[dict]:
        return get_abilities(hero_key)

    def _find_existing(self, hero: str, ability: str, slot: int) -> Optional[str]:
        for id_, cd in self._active.items():
            if cd.hero == hero and cd.ability == ability and cd.player_slot == slot:
                return id_
        return None
